### ISSUE TITLE
Activity has leaked IntentReceiver 

### ISSUE THREAD

**Issue by iamjpsharma** [meny1122/MarqueeTextNews#3]
Activity has leaked IntentReceiver meny1122.com.marqueetextnews.NetworkReceiver@b7478a7 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by iamjpsharma** [comment]
android.app.IntentReceiverLeaked: Activity PopupActivity has leaked IntentReceiver meny1122.com.marqueetextnews.NetworkReceiver@4958205 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1620)
                                                                                                    	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1396)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1624)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1590)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1578)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:679)
                                                                                                    	at meny1122.com.marqueetextnews.MarqueeTextNews.setNetworkReceiver(MarqueeTextNews.kt:128)
                                                                                                    	at meny1122.com.marqueetextnews.MarqueeTextNews.<init>(MarqueeTextNews.kt:38)
                                                                                                    	at meny1122.com.marqueetextnews.MarqueeTextNews.<init>(MarqueeTextNews.kt:22)
                                                                                                    	at meny1122.com.marqueetextnews.MarqueeTextNews.<init>(Unknown Source:6)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1012)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1142)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1103)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1103)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
                                                                                                    	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:459)
                                                                                                    	at android.app.Activity.setContentView(Activity.java:3584)
                                                                                                    	at Activity.PopupActivity.onCreate(PopupActivity.java:118)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8142)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8114)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3579)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8097)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
